# Numpy exercises


This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/Rakib1508/python-data-science. File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [1]:
# Ucomment the next line if you need install numpy
!pip install numpy --upgrade --quiet

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
z = np.zeros((10, 10))
print('%d bytes' % (z.size * z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# when python path is on the same directory
# %run 'python -c "import numpy; numpy.info(numpy.add)"'
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
z = np.arange(50)
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0] (★☆☆)

In [11]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
z = np.random.rand(3, 3, 3)
z

array([[[0.49313669, 0.71868791, 0.19807027],
        [0.94891374, 0.6194095 , 0.77056697],
        [0.45652037, 0.17960753, 0.75868341]],

       [[0.39608093, 0.74315149, 0.94404107],
        [0.90272467, 0.03251306, 0.51979251],
        [0.65048173, 0.18490443, 0.03806093]],

       [[0.33894871, 0.11192964, 0.43837556],
        [0.9952383 , 0.14174319, 0.85374242],
        [0.30553229, 0.14590562, 0.35346927]]])

In [14]:
z = np.random.random((3, 3, 3))
z

array([[[0.79601576, 0.25436403, 0.43646439],
        [0.35629607, 0.44187905, 0.72478732],
        [0.12133874, 0.13142168, 0.28933881]],

       [[0.04672047, 0.112821  , 0.10390854],
        [0.62107743, 0.56736195, 0.64131369],
        [0.83501982, 0.37461794, 0.40955594]],

       [[0.7048493 , 0.25304524, 0.32698671],
        [0.93811634, 0.77519172, 0.44012367],
        [0.9201436 , 0.22907169, 0.39268786]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
z = np.random.random((10, 10))
z_min, z_max = z.min(), z.max()
print('z_min = ', z_min)
print('z_max = ', z_max)
print(z)

z_min =  0.006350614079751682
z_max =  0.9854737739136576
[[0.89508904 0.54204324 0.47588818 0.50908223 0.55168749 0.20543505
  0.6448959  0.20164779 0.5426194  0.59767789]
 [0.26768734 0.65157386 0.01682447 0.26784988 0.56671573 0.68956516
  0.19649671 0.43905278 0.06251504 0.1568566 ]
 [0.80464212 0.53543482 0.29741578 0.00635061 0.8513295  0.47918739
  0.58185888 0.81999676 0.02168407 0.7502456 ]
 [0.39103276 0.46144432 0.50974303 0.24249853 0.42327002 0.5479834
  0.0920274  0.04676612 0.82260507 0.81914138]
 [0.02527505 0.18826251 0.32287007 0.00813577 0.60647812 0.76303951
  0.62214875 0.53614063 0.4123543  0.38610445]
 [0.7933292  0.73494299 0.92182625 0.713602   0.57479336 0.76383249
  0.6771545  0.09460441 0.02196147 0.56178701]
 [0.93578839 0.30125635 0.40816177 0.54209386 0.06762098 0.8405575
  0.7735169  0.690215   0.08964227 0.95510249]
 [0.30365153 0.4234542  0.17606101 0.16078369 0.04970619 0.63827873
  0.73623437 0.71062201 0.19743802 0.21852273]
 [0.35588729 0.75020624 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
z = np.random.random(30)
mean = z.mean()
print('mean: ', mean)
print(z)

mean:  0.3702401451097231
[0.19460005 0.34124533 0.01810886 0.01393916 0.7250346  0.3185703
 0.16471826 0.1094814  0.38303314 0.55125242 0.05485286 0.54828927
 0.59894607 0.1320662  0.63868437 0.81644335 0.28116366 0.14215171
 0.81784762 0.06230796 0.44818087 0.94424721 0.08300443 0.44122829
 0.7395257  0.48204197 0.16977489 0.4032336  0.47243294 0.01079786]


#### 15. Create a 2D array with 1 on the border and 0 inside (★☆☆)

In [17]:
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
z = np.ones((5, 5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
z = np.ones((5, 5))
# using fancy index
z[:, [0, -1]] = 0
print(z)

[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]]


In [20]:
z = np.ones((5, 5))
# again fancy index
z[[0, -1], :] = 0
print(z)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
z = np.diag(1+np.arange(4), k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
z = np.zeros((8, 8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
print(np.unravel_index(99, (6, 7, 8)))
z = np.array((6, 7, 8))
i = np.unravel_index(99, z)
print(i)

(1, 5, 3)
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
z = np.random.random((5, 5))
normalized_z = (z - np.mean(z)) / np.std(z)
print(z)
print('\n\n')
print('normalized matrix')
print(normalized_z)

[[0.06164483 0.04078186 0.63834698 0.13402489 0.18358354]
 [0.0824161  0.52432232 0.34631807 0.14220781 0.57886705]
 [0.43075105 0.22439634 0.51377917 0.42303691 0.8515974 ]
 [0.90176754 0.03634496 0.35553969 0.10328129 0.63817965]
 [0.4967103  0.27143812 0.3375726  0.72466956 0.74939138]]



normalized matrix
[[-1.27638925 -1.35708551  0.95424691 -0.99642917 -0.80474042]
 [-1.19604771  0.51320898 -0.17529675 -0.96477832  0.72418346]
 [ 0.15128302 -0.64687988  0.47242892  0.12144537  1.77908186]
 [ 1.97313582 -1.37424704 -0.13962829 -1.11534288  0.95359967]
 [ 0.40640796 -0.46492619 -0.2091235   1.2881355   1.38375743]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([
    ('r', np.ubyte),
    ('g', np.ubyte),
    ('b', np.ubyte),
    ('a', np.ubyte)
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [29]:
# shortcut way
z = np.ones((5, 3)) @ np.ones((3, 2))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
z = np.arange(11)
z[(3<z) & (z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
z = np.arange(11)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
z ** z

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [34]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [35]:
z <- z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [36]:
1j * z

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [37]:
z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [39]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
z = np.random.uniform(-10, +10, 10)
print(z)
print(np.copysign(np.ceil(np.abs(z)), z))

[ 9.06480697 -6.52984091  1.19377707 -9.35990757 -7.12707608  2.96827912
 -3.72343976 -2.98914004 -5.13406536  6.61315797]
[ 10.  -7.   2. -10.  -8.   3.  -4.  -3.  -6.   7.]


In [41]:
# readable but less efficient
print(z)
print(np.where(z>0, np.ceil(z), np.floor(z)))

[ 9.06480697 -6.52984091  1.19377707 -9.35990757 -7.12707608  2.96827912
 -3.72343976 -2.98914004 -5.13406536  6.61315797]
[ 10.  -7.   2. -10.  -8.   3.  -4.  -3.  -6.   7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
z1 = np.random.randint(0, 10, 10)
print(z1)

[8 3 9 8 3 6 0 0 0 1]


In [43]:
z2 = np.random.randint(0, 10, 10)
print(z2)

[9 9 1 8 4 7 3 4 9 0]


In [44]:
print(np.intersect1d(z1, z2))

[0 1 3 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [45]:
# suicidal mode
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0
z

array([inf])

In [46]:
# back to sanity
a = np.seterr(**defaults)
a

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [47]:
# with context manager
with np.errstate(all='ignore'):
    a = np.arange(3) / 0
    print(a)

[nan inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:
yesterday = np.datetime64('today') - np.timedelta64(1)
yesterday

numpy.datetime64('2021-07-16')

In [50]:
today = np.datetime64('today')
today

numpy.datetime64('2021-07-17')

In [51]:
tomorrow = np.datetime64('today') + np.timedelta64(1)
tomorrow

numpy.datetime64('2021-07-18')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [53]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print(A)
print(B)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [54]:
z = np.random.uniform(0, 10, 10)
z

array([0.24424834, 1.09941879, 9.41812539, 6.96155798, 9.0384386 ,
       4.42553668, 9.14246909, 2.03094412, 3.21542354, 3.32585038])

In [55]:
print(z - z%1)

[0. 1. 9. 6. 9. 4. 9. 2. 3. 3.]


In [56]:
print(z // 1)

[0. 1. 9. 6. 9. 4. 9. 2. 3. 3.]


In [57]:
print(np.floor(z))

[0. 1. 9. 6. 9. 4. 9. 2. 3. 3.]


In [58]:
print(z.astype(int))

[0 1 9 6 9 4 9 2 3 3]


In [59]:
print(np.trunc(z))

[0. 1. 9. 6. 9. 4. 9. 2. 3. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [60]:
# using broadcasting
z = np.zeros((5, 5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [61]:
# without broadcasting
z = np.tile(np.arange(0, 5), (5, 1))
print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [62]:
def generate():
    for x in range(10):
        yield x

In [63]:
z = np.fromiter(generate(), dtype=float, count=-1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [64]:
z = np.linspace(0, 1, 11, endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [65]:
z = np.random.random(10)
z.sort()
print(z)

[0.13250781 0.2537234  0.44250637 0.44540322 0.58086562 0.61394647
 0.85243816 0.87760229 0.8939968  0.92134399]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [66]:
z = np.arange(10)
print(z)
np.add.reduce(z)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [67]:
A = np.random.randint(0, 2, 5)
print(A)
B = np.random.randint(0, 2, 5)
print(B)

# assuming identical shape of array and tolerance for comparison of values
equal = np.allclose(A, B)
print(equal)

# checking both shape nad element values, no tolerance
equal = np.array_equal(A, B)
print(equal)

[1 1 0 1 0]
[1 1 1 0 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [69]:
z = np.random.random((10, 2))
X, Y = z[:, 0], z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)
final = np.vstack((R, T)).T
print(final)

[0.90414948 0.80980943 1.01816797 0.72177586 1.2047706  0.92953962
 0.77347369 0.29449176 0.52854347 0.51282656]
[1.21629146 0.46333135 0.9293817  0.21704195 0.82300053 1.0251445
 1.02678934 1.50660704 1.28949801 1.09660505]
[[0.90414948 1.21629146]
 [0.80980943 0.46333135]
 [1.01816797 0.9293817 ]
 [0.72177586 0.21704195]
 [1.2047706  0.82300053]
 [0.92953962 1.0251445 ]
 [0.77347369 1.02678934]
 [0.29449176 1.50660704]
 [0.52854347 1.28949801]
 [0.51282656 1.09660505]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [70]:
z = np.random.random(10)
# print(z)
z[z.argmax()] = 0
print(z)

[0.11920729 0.63021036 0.         0.69943026 0.10621915 0.70218099
 0.07001595 0.35718079 0.1692531  0.26329689]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [71]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [72]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print('\nDeterminant')
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]

Determinant
3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [73]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype)
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    print('\n')

for dtype in [np.float32, np.float64]:
    print(dtype)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print('\n')

<class 'numpy.int8'>
-128
127


<class 'numpy.int32'>
-2147483648
2147483647


<class 'numpy.int64'>
-9223372036854775808
9223372036854775807


<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07


<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16




#### 49. How to print all the values of an array? (★★☆)

In [74]:
np.set_printoptions(threshold=float('inf'))
z = np.zeros((40, 40))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [75]:
z = np.arange(100)
v = np.random.uniform(0, 100)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

37.91624619406012
38


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [76]:
z = np.zeros(10, [
    ('position', [
        ('x', float, 1),
        ('y', float, 1)
    ]),
    ('color', [
        ('r', float, 1),
        ('g', float, 1),
        ('b', float, 1),
    ])
])
print(z)
print(z[1])

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
((0., 0.), (0., 0., 0.))


C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/1335918533.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [77]:
Z = np.random.random((100, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.30061645 0.86409691 0.33086626 0.58818291 0.30366984
  0.25722336 0.67842395 0.25211899 0.98055545 0.63969708 0.87131073
  0.44876543 0.39526482 0.23219925 0.28794057 0.60172238 0.5131445
  0.86669583 0.35348075 0.68726331 0.55926566 0.17616822 0.37779975
  0.71043143 0.15417619 0.70758556 0.49411305 0.82555345 0.64725136
  0.46180126 0.73774315 0.47838141 0.47565267 0.42977448 0.52202567
  0.71358403 0.15593973 0.50936566 0.19328132 0.50224698 0.29348822
  0.40802038 0.48773353 0.71617799 0.78539255 0.2597325  0.07153954
  0.13473647 0.61367253 0.28814612 0.55021554 0.75361302 0.40776094
  0.69528492 0.69122252 0.07069418 0.47476228 0.354626   0.36317463
  0.79838511 1.03117598 0.08778124 0.83012659 0.62002514 0.65525425
  0.29695589 0.40169748 0.44181988 0.21378675 0.63704878 0.61332967
  0.63717594 0.40425423 0.74699214 0.47681858 0.42177363 0.21378999
  0.71531525 0.08894495 0.67988775 0.20470259 0.70075147 0.4886965
  0.63789979 0.52602285 0.44197822 0.88457954 0.35

In [78]:
# much faster and simpler with scipy
import scipy
import scipy.spatial

Z = np.random.random((100, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[0.         0.91543496 1.23623167 0.19243508 0.60160596 0.91213297
  0.51640045 1.02656516 0.39455537 0.57879078 0.85475312 1.00840616
  0.71560475 0.37291979 0.47418761 0.79410497 0.29156581 0.28196425
  0.46245811 0.61640401 0.79079382 1.16668544 0.7525694  0.04736006
  0.73586693 0.93973314 0.46561619 0.22698051 0.95721687 0.27446956
  0.49725029 0.9538846  1.04680366 0.78335639 0.9995637  0.80881182
  0.78804468 0.71448631 0.83481678 0.65298161 0.59261799 0.24650434
  0.93178767 0.57814199 1.10045823 0.53161684 0.70680671 0.82349564
  0.57120386 0.55142556 0.37971523 0.42279395 0.64748091 0.39816044
  0.73166255 0.63516857 0.71142887 0.49139878 0.77535946 1.00468809
  0.15596198 0.84409197 0.75792361 0.69027679 1.20366413 0.90554904
  1.0079796  0.62254431 1.00493284 0.96319185 0.25141727 0.52073672
  0.88156217 0.65448532 0.74167275 0.19825391 0.80752726 1.11347858
  0.89388025 0.8594724  0.75807292 0.91465801 0.32425391 0.26893204
  0.59417479 0.99169554 0.82071784 0.25222578 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [79]:
z = (np.random.rand(10) * 100).astype(np.float32)
print(z)
y = z.view(np.int32)
y[:] = z
print(y)

[ 4.2652717 81.86335   87.70825   34.01418   49.930138  64.44946
 20.149626  48.94102   87.16499   70.46962  ]
[ 4 81 87 34 49 64 20 48 87 70]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [80]:
from io import StringIO

# fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
z = np.genfromtxt(s, delimiter=',', dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/3812643813.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = np.genfromtxt(s, delimiter=',', dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [81]:
z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(z):
    print(index, value)
print('\n')
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [82]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [83]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print(z)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [84]:
x = np.random.rand(5, 10)

# new version of numpy
y = x - x.mean(axis=1, keepdims=True)
print('New version\n', y, '\n\n')

# older versions of numpy
y = x - x.mean(axis=1).reshape(-1, 1)
print('Older version\n', y)

New version
 [[-0.37700753  0.28672665 -0.13738074 -0.4228735   0.32061282 -0.1749878
   0.17372188 -0.39721237  0.26750723  0.46089336]
 [-0.15954227  0.11937474 -0.06525289  0.16408726 -0.00320837  0.27277695
  -0.18195293 -0.06291273  0.04577267 -0.12914244]
 [-0.24489459 -0.48363177 -0.26789091  0.40727885  0.34627281 -0.23307579
  -0.37023736  0.19755461  0.24797161  0.40065253]
 [-0.18235556  0.2344628  -0.21419267 -0.1581455   0.57306659 -0.05996833
  -0.1831944  -0.10291495  0.24414808 -0.15090607]
 [ 0.35362288  0.31684056  0.11368572 -0.13504756 -0.4973299   0.20675055
  -0.57172766 -0.19444138  0.27834295  0.12930383]] 


Older version
 [[-0.37700753  0.28672665 -0.13738074 -0.4228735   0.32061282 -0.1749878
   0.17372188 -0.39721237  0.26750723  0.46089336]
 [-0.15954227  0.11937474 -0.06525289  0.16408726 -0.00320837  0.27277695
  -0.18195293 -0.06291273  0.04577267 -0.12914244]
 [-0.24489459 -0.48363177 -0.26789091  0.40727885  0.34627281 -0.23307579
  -0.37023736  0.1975

#### 59. How to sort an array by the nth column? (★★☆)

In [85]:
z = np.random.randint(0, 10, (3, 3))
print(z)
print(z[z[:, 1].argsort()])

[[1 2 8]
 [3 5 8]
 [1 0 0]]
[[1 0 0]
 [1 2 8]
 [3 5 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [86]:
z = np.random.randint(0, 3, (3, 10))
print((~z.any(axis=0)).any())
print(z)

False
[[0 1 2 1 1 1 0 1 1 2]
 [0 0 0 2 0 2 0 0 2 2]
 [1 2 2 0 2 0 1 1 2 1]]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [87]:
z = np.random.uniform(0, 1, 10)
x = 0.5
m = z.flat[np.abs(z - x).argmin()]
print(m)
print(z)

0.4940937902947916
[0.10062806 0.49409379 0.77933465 0.74177331 0.1212263  0.45752136
 0.97484731 0.60937509 0.61575712 0.06341306]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [88]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
i = np.nditer([A, B, None])
for x, y, z in i:
    z[...] = x + y
print(A)
print(B)
print(i.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [89]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', 'no name')

z = NamedArray(np.arange(10), 'range_10')
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [90]:
z = np.ones(10)
print('z =', z)
i = np.random.randint(0, len(z), 20)
print('i =', i)
z += np.bincount(i, minlength=len(z))
print(z)

z = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
i = [7 8 3 2 5 4 7 2 9 9 8 9 2 9 7 2 3 0 1 7]
[2. 2. 5. 3. 2. 2. 1. 5. 3. 5.]


In [91]:
# another solution
z = np.ones(10)
print('z =', z)
i = np.random.randint(0, len(z), 20)
print('i =', i)
np.add.at(z, i, 1)
print(z)

z = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
i = [3 9 5 5 3 2 7 4 1 7 1 9 9 5 4 5 6 9 6 1]
[1. 4. 2. 3. 3. 5. 3. 3. 1. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [92]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [93]:
w, h = 256, 256
i = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1, 3), axis=0)
print(len(colors))

64


In [94]:
# faster version
w, h = 256, 256
i = np.random.randint(0, 4, (h, w, 3), dtype=np.uint8)

# view each pixel as a single 24-bit int, rather than three 8-bit bytes
I24 = np.dot(i.astype(np.uint32), [1, 256, 65536])

# count unique colors
n = len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [95]:
A = np.random.randint(0, 10, (3, 4, 3, 4))

# solution by passing tuple of axes
result = A.sum(axis=(-2, -1))
print(result)

# solution by flattening the last two dimensions into one
result = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(result)

[[54 47 49 51]
 [72 36 67 48]
 [52 69 63 41]]
[[54 47 49 51]
 [72 36 67 48]
 [52 69 63 41]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [96]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52447075 0.57061638 0.42405689 0.14580932 0.38886996 0.49265413
 0.4905798  0.52837985 0.39453177 0.58175558]


In [97]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.524471
1    0.570616
2    0.424057
3    0.145809
4    0.388870
5    0.492654
6    0.490580
7    0.528380
8    0.394532
9    0.581756
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [98]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

# slow version
print(np.diag(np.dot(A, B)))

# fast version
print(np.sum(A * B.T, axis=1))

# fastest version
print(np.einsum('ij, ji -> i', A, B))

[1.04372216 1.39059488 0.90748075 0.50597125 0.48853103]
[1.04372216 1.39059488 0.90748075 0.50597125 0.48853103]
[1.04372216 1.39059488 0.90748075 0.50597125 0.48853103]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
z = np.array([1, 2, 3, 4, 5])
nz = 3
z0 = np.zeros(len(z) + (len(z)-1) * (nz))
print(z0)
z0[::nz+1] = z
print(z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [100]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [101]:
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [102]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 2, 33) ( 2, 64) ( 9, 57) ( 9, 80) (10, 25) (10, 74) (11, 17) (11, 66)
 (17, 66) (18, 43) (18, 88) (25, 74) (31, 35) (31, 83) (33, 64) (35, 83)
 (37, 39) (37, 77) (39, 77) (43, 88) (57, 80) (61, 66) (61, 74) (66, 74)
 (69, 70) (69, 96) (70, 96) (82, 84) (82, 97) (84, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [103]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [104]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

In [105]:
z = np.arange(20)
print(z)
print(moving_average(z, n=4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [106]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

In [107]:
z = rolling(np.arange(10), 3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [108]:
z = np.random.randint(0, 2, 100)
np.logical_not(z, out=z)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [109]:
np.random.uniform(-1.0, 1.0, 100)
np.negative(z, out=z)

array([ 0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0,  0, -1, -1,  0,
       -1,  0,  0, -1, -1, -1,  0, -1,  0,  0, -1,  0,  0, -1,  0, -1, -1,
        0,  0, -1,  0, -1,  0,  0, -1, -1,  0, -1,  0, -1,  0,  0, -1,  0,
       -1, -1, -1,  0, -1,  0,  0, -1, -1,  0, -1,  0, -1,  0, -1, -1, -1,
        0, -1,  0,  0, -1,  0, -1, -1, -1,  0, -1,  0, -1,  0,  0, -1, -1,
        0, -1,  0,  0, -1, -1,  0, -1, -1, -1, -1, -1,  0,  0, -1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [110]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

In [111]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[ 1.2179644  15.33401156 15.81249195  3.09318409  0.37518797  4.02402631
 13.5057104   1.30616861  1.20096485 12.99003234]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [112]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[10.42438523 10.84912409 11.84420183 14.15896037  7.80232694  6.02895606
  12.11923659 10.44380326 15.18716757  5.13270144]
 [ 4.09560735  6.20936833 13.31695259 12.35628897 10.91112944  9.88379473
  14.70542362 14.36079257 11.79261556  8.77168663]
 [10.41280085  9.26412047  8.43140073 11.32018672  4.41671161  2.74431942
   8.69870095  7.17068398 12.9381599   1.81200191]
 [ 1.78077421  2.30749701  5.5661634   3.1126849   4.7440254   4.67533298
   7.96238993  9.24048271  2.65318437  3.26757977]
 [ 6.69254575  8.7078615   0.64419429  3.32138364  1.13475452  1.82194679
   3.88720652  6.45558135  3.96390997  0.18333339]
 [ 4.7351946   1.702995    2.38924257  3.59007204  0.1055762   0.89393911
   3.63434847  3.61276612  5.05769638  2.09679601]
 [ 3.53030079  6.86551053  1.1228347   3.27669987  1.44244271  1.09794217
   1.56088621  3.5080809   2.94489271  2.63947021]
 [ 6.88235516 11.28155434  4.58604448  7.75415212  4.00905935  3.14566398
   1.32473007  1.50744468  7.52917072  4.8458314 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [113]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 7 4 6 7 6 6 7 9 6]
 [7 2 4 3 4 3 2 5 0 8]
 [2 8 0 8 4 4 5 8 1 2]
 [5 8 1 9 8 6 3 3 7 5]
 [0 8 0 5 5 8 1 2 0 6]
 [5 5 5 4 2 6 1 2 6 5]
 [7 6 7 1 0 9 3 9 9 0]
 [5 0 8 3 0 7 5 9 2 5]
 [1 0 9 8 6 8 9 7 9 1]
 [8 5 3 1 0 3 8 0 5 1]]
[[0 0 0 0 0]
 [0 0 7 4 6]
 [0 7 2 4 3]
 [0 2 8 0 8]
 [0 5 8 1 9]]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_3108/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [114]:
z = np.arange(1, 15, dtype=np.uint32)
r = stride_tricks.as_strided(z, (11, 4), (4, 4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [115]:
z = np.random.uniform(0, 1, (10, 10))
u, s, v = np.linalg.svd(z) # singular value decomposition
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [116]:
z = np.random.randint(0, 10, 50)
print(np.bincount(z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [117]:
z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (z.shape[0] - 3)
j = 1 + (z.shape[1] - 3)
c = stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print(c)

[[[[0 1 2]
   [0 0 2]
   [0 3 2]]

  [[1 2 2]
   [0 2 1]
   [3 2 3]]

  [[2 2 0]
   [2 1 3]
   [2 3 2]]

  [[2 0 3]
   [1 3 0]
   [3 2 4]]

  [[0 3 1]
   [3 0 4]
   [2 4 0]]

  [[3 1 2]
   [0 4 1]
   [4 0 4]]

  [[1 2 2]
   [4 1 0]
   [0 4 4]]

  [[2 2 2]
   [1 0 0]
   [4 4 2]]]


 [[[0 0 2]
   [0 3 2]
   [2 2 4]]

  [[0 2 1]
   [3 2 3]
   [2 4 0]]

  [[2 1 3]
   [2 3 2]
   [4 0 3]]

  [[1 3 0]
   [3 2 4]
   [0 3 1]]

  [[3 0 4]
   [2 4 0]
   [3 1 4]]

  [[0 4 1]
   [4 0 4]
   [1 4 3]]

  [[4 1 0]
   [0 4 4]
   [4 3 0]]

  [[1 0 0]
   [4 4 2]
   [3 0 1]]]


 [[[0 3 2]
   [2 2 4]
   [2 4 3]]

  [[3 2 3]
   [2 4 0]
   [4 3 0]]

  [[2 3 2]
   [4 0 3]
   [3 0 3]]

  [[3 2 4]
   [0 3 1]
   [0 3 4]]

  [[2 4 0]
   [3 1 4]
   [3 4 4]]

  [[4 0 4]
   [1 4 3]
   [4 4 0]]

  [[0 4 4]
   [4 3 0]
   [4 0 0]]

  [[4 4 2]
   [3 0 1]
   [0 0 4]]]


 [[[2 2 4]
   [2 4 3]
   [2 3 1]]

  [[2 4 0]
   [4 3 0]
   [3 1 0]]

  [[4 0 3]
   [3 0 3]
   [1 0 3]]

  [[0 3 1]
   [0 3 4]
   [0 3 1]]

  [[3 1 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [118]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 14  7  9  5]
 [14  0 13 14 15]
 [ 7 13  7 42  5]
 [ 9 14 42  0 17]
 [ 5 15  5 17  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of the p matrix products at once? (result has shape (n,1)) (★★★)

In [119]:
p, n = 10, 20
m = np.ones((p, n, n))
v = np.ones((p, n, 1))
s = np.tensordot(m, v, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [120]:
z = np.ones((16, 16))
k = 4
s = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0), np.arange(0, z.shape[1], k), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [121]:
# alternative solution
z = np.ones((16, 16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(z, (k, k))
s = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [122]:
def iterate(z):
    n = (
        z[0:-2, 0:-2] + z[0:-2, 1:-1] + z[0:-2, 2:] +
        z[1:-1, 0:-2] + z[1:-1, 2:] +
        z[2:, 0:-2] + z[2:, 1:-1] + z[2:, 2:]
    )
    birth = (n==3) & (z[1:-1, 1:-1]==0)
    survive = ((n==2) | (n==3)) & (z[1:-1, 1:-1]==1)
    z[...] = 0
    z[1:-1, 1:-1][birth | survive] = 1
    return z

In [123]:
z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    z = iterate(z)
print(z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1

#### 89. How to get the n largest values of an array (★★★)

In [124]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5

# slow
print(z[np.argsort(z)[-n:]])

# fast
print(z[np.argpartition(-z, n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [125]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

In [126]:
print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [127]:
z = np.array([
    ('Hello', 2.5, 3),
    ('World', 3.6, 2)
])
r = np.core.records.fromarrays(
    z.T, names='col1, col2, col3',
    formats='S8, f8, i8'
)
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [128]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z, 3)
%timeit Z * Z * Z
%timeit np.einsum('i, i, i -> i', Z, Z, Z)

1.87 s ± 43.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
307 ms ± 18.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
174 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [129]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[0 1 3 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [130]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 0 1]
 [2 2 0]
 [2 1 3]
 [2 4 0]
 [2 1 3]
 [2 3 1]
 [3 0 0]
 [0 2 1]
 [2 4 1]
 [4 0 2]]
[[4 0 1]
 [2 2 0]
 [2 1 3]
 [2 4 0]
 [2 1 3]
 [2 3 1]
 [3 0 0]
 [0 2 1]
 [2 4 1]
 [4 0 2]]
[[4 0 1]
 [2 2 0]
 [2 1 3]
 [2 4 0]
 [2 1 3]
 [2 3 1]
 [3 0 0]
 [0 2 1]
 [2 4 1]
 [4 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [131]:
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
b = ((i.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(b[:, ::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [132]:
# another solution
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(i[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [133]:
z = np.random.randint(0, 2, (6, 3))
t = np.ascontiguousarray(z).view(np.dtype((np.void, z.dtype.itemsize * z.shape[1])))
_, idx = np.unique(t, return_index=True)
print(z[idx])

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


In [134]:
# elegent
print(np.unique(z, axis=0))

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [135]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

print(np.einsum('i->', A)) # np.sum(A)
print(np.einsum('i,i -> i', A, B)) # A * B
print(np.einsum('i, i', A, B)) # np.inner(A, B)
print(np.einsum('i,j -> ij', A, B)) # np.outer(A, B)

5.678216392965167
[0.29582444 0.0687446  0.59770949 0.5591423  0.00114866 0.20131919
 0.02878227 0.02582941 0.55540855 0.20804319]
2.5419520965663183
[[2.95824437e-01 7.55941852e-02 3.69013341e-01 2.94659788e-01
  6.67251539e-04 2.13938628e-01 2.41352440e-02 1.41923842e-02
  2.28763287e-01 1.47257534e-01]
 [2.69019790e-01 6.87445974e-02 3.35577048e-01 2.67960670e-01
  6.06791888e-04 1.94553652e-01 2.19483499e-02 1.29064125e-02
  2.08035049e-01 1.33914531e-01]
 [4.79161732e-01 1.22443707e-01 5.97709485e-01 4.77275293e-01
  1.08078091e-03 3.46527165e-01 3.90930697e-02 2.29881192e-02
  3.70539412e-01 2.38520441e-01]
 [5.61352324e-01 1.43446471e-01 7.00234568e-01 5.59142304e-01
  1.26616721e-03 4.05966955e-01 4.57987023e-02 2.69312703e-02
  4.34098022e-01 2.79433842e-01]
 [5.09254938e-01 1.30133645e-01 6.35247947e-01 5.07250023e-01
  1.14865812e-03 3.68290408e-01 4.15482653e-02 2.44318618e-02
  3.93810717e-01 2.53500445e-01]
 [2.78374856e-01 7.11351661e-02 3.47246620e-01 2.77278906e-01
  6

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [136]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**0.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [137]:
x = np.asarray([
    [1.0, 0.0, 3.0, 8.0],
    [2.0, 0.0, 1.0, 1.0],
    [1.5, 2.5, 1.0, 0.0]
])
n = 4
m = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [138]:
x = np.random.randn(100) # random 1D array
n = 1000 # number of bootstrapped samples
idx = np.random.randint(0, x.size, (n, x.size))
means = x[idx]
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-1.84889252  1.9785297 ]


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/Rakib1508/python-data-science